# Generated by Django 5.1.6 on 2025-02-22 19:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=5, unique=True)),
                ('description', models.TextField()),
                ('student_registration_number', models.CharField(max_length=50)),
                ('year_of_study', models.CharField(choices=[('first_year', 'First Year'), ('second_year', 'Second Year'), ('third_year', 'Third Year')], max_length=100)),
                ('course_code', models.CharField(max_length=20)),
                ('semester', models.CharField(choices=[('semester_1', 'Semester One'), ('semester_2', 'Semester Two'), ('semester_3', 'Semester Three')], max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('forwarded', 'Forwarded'), ('resolved', 'Resolved')], default='submitted', max_length=20)),
                ('resolution_details', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_issues', to=settings.AUTH_USER_MODEL)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.college')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to=settings.AUTH_USER_MODEL)),
                ('forwarded_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forwarded_issues', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(choices=[('missing_marks', 'Missing Marks'), ('exam_remark', 'Examination Remark'), ('missed_test', 'Missed Test')], on_delete=django.db.models.deletion.CASCADE, to='issues.issuecategory')),
            ],
        ),
    ]
