# Generated by Django 5.1.6 on 2025-02-24 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issues.issuecategory'),
        ),
        migrations.AlterField(
            model_name='issuecategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
