# Generated by Django 5.1.7 on 2025-03-23 16:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_course'),
        ('issues', '0002_alter_issue_semester_alter_issue_year_of_study'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='course_code',
        ),
        migrations.AddField(
            model_name='issue',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='issue',
            name='course_unit',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.courseunit'),
            preserve_default=False,
        ),
    ]
