# Generated by Django 5.1.7 on 2025-03-23 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_customuser_course'),
        ('issues', '0003_remove_issue_course_code_issue_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='student_registration_number',
        ),
        migrations.AlterField(
            model_name='issue',
            name='course_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.courseunit'),
        ),
    ]
