# Generated by Django 5.1.7 on 2025-03-16 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_options_issue_attachment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='attachment',
        ),
        migrations.AddField(
            model_name='issue',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments/'),
        ),
    ]
