# Generated by Django 5.1.7 on 2025-03-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_remove_issue_attachments_remove_issue_forwarded_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='token',
            field=models.CharField(blank=True, max_length=24, unique=True),
        ),
    ]
