# Generated by Django 5.1.7 on 2025-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0005_remove_issue_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
