# Generated by Django 5.1.7 on 2025-03-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('registrar', 'Registrar'), ('lecturer', 'Lecturer'), ('student', 'Student')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
