# Generated by Django 5.1.7 on 2025-03-20 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_college_alter_customuser_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseunit',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2')], default=1),
        ),
        migrations.AddField(
            model_name='courseunit',
            name='year_taken',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], default=1),
        ),
    ]
