# Generated by Django 5.1.7 on 2025-03-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_college_code_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='years',
            field=models.IntegerField(default=3),
        ),
    ]
