# Generated by Django 5.1.4 on 2025-04-01 17:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_course_school_alter_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnifiedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('token_type', models.CharField(choices=[('email_verification', 'Email Verification'), ('password_reset', 'Password Reset')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
