# Generated by Django 5.1.4 on 2025-04-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_unifiedtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_verified',
            field=models.DateField(blank=True, null=True),
        ),
    ]
