name: Server Deployment

on:
  push:
    branches: ["main"]
    paths: ["server/**"]  # Only run when files under the 'server' directory change

jobs:
  build:
    defaults:
      run:
        working-directory: ./server  # Execute commands in the ./server directory
    runs-on: self-hosted           # Use the self-hosted runner on your VPS

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0             # Pull full git history, useful for diffs and rollback
          persist-credentials: false # Do not keep credentials after checkout
          clean: false               # Preserve untracked files like .env

      - name: Create .env
        run: |
          # Create .env from secrets, stripping any carriage returns
          echo "${{ secrets.SERVER_SECRETS }}" | tr -d '\r' > .env

      - name: Deploy & prune       # Combined deployment and cleanup step
        run: |
          # Build images without cache to ensure fresh builds
          docker compose build --no-cache
          # Deploy containers, removing any orphaned services to prevent conflicts
          docker compose up -d --remove-orphans
          # Prune all unused Docker objects including images, containers, and volumes
          docker system prune -af --volumes
          # Clear BuildKit cache to reclaim additional space
          docker builder prune --all --force
