name: Server Deployment

on:
  push:
    branches: ["main"]
    paths:
      - "server/**"  # Trigger only when files in the 'server' directory change

jobs:
  build:
    defaults:
      run:
        working-directory: ./server
    runs-on: self-hosted

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          clean: false  # Avoid deleting .env or untracked files

      # Create the .env file from SERVER_SECRETS (handles multi-line secrets correctly)
      - name: Create .env file
        run: |
          echo "${{ secrets.SERVER_SECRETS }}" | tr -d '\r' > .env

      # Build and restart containers safely (without downtime)
      - name: Deploy with Docker Compose
        run: |
          docker compose build --no-cache  # Build latest image
          docker compose up -d --remove-orphans  # Restart services with zero downtime
          
          # Cleanup old, unused images to free up disk space
          docker image prune -af